/* Screenshots in reference/new details define amounts; IMG_4040 defines gestures. */
window.createLedger=({header,icon,money,navigate,render,showModal,closeModal,choices,service,getRoute})=>{
  const entries=[
    {id:'transfer-large',month:'2023-12',day:'12.8',date:'2023-12-08',label:'转账-张建生(8896)',time:'02:51',amount:6135277.76,balance:6136277.76},
    {id:'transfer-initial',month:'2023-12',day:'12.8',date:'2023-12-08',label:'转账-张建生(8896)',time:'02:51',amount:1000,balance:1000},
    {id:'deposit-opening',month:'2024-01',day:'1.1',date:'2024-01-01',label:'开户起息，产品代码：XDC048069',time:'09:51',amount:-6136277.76,balance:0}
  ];
  let month='all',filter='全部',selected=entries[0],pickerMode='month',year=new Date().getFullYear(),pickMonth=new Date().getMonth()+1,rangeStart='2026-09-01',rangeEnd='2026-09-05',custom=false;
  const excluded=new Set(entries.map(r=>r.id));
  const amount=r=>(r.amount>0?'+':'-')+'¥'+money(Math.abs(r.amount));
  const refresh=()=>render(document.querySelector?.('#app [data-scroll]')?.scrollTop||0);
  function top(){return `<header class="page-header ledger-header"><div class="nav"><button data-action="back" aria-label="返回">${icon('back')}</button><h1 tabindex="-1">收支</h1><button data-action="ledger-search" aria-label="搜索"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="10" cy="10" r="8"/><path d="m16 16 6 6"/></svg></button><button data-action="menu" aria-label="更多">···</button></div></header>`;}
  const tabs=()=>`<nav class="ledger-tabs"><button class="selected" data-action="ledger-list"><span>¥</span>明细</button><button data-action="ledger-book"><span>▤<i></i></span>账本</button></nav>`;
  function rows(list){return list.map(r=>`<button class="income-row ledger-row" data-action="income-item" data-value="${r.id}"><span class="ledger-icon">${r.amount<0?'♙':'⇄'}</span><span class="ledger-label">${r.label}</span>${excluded.has(r.id)?'<em>不计入</em>':'<em class="included">计入</em>'}<strong>${amount(r)}</strong><small class="ledger-time">${r.time}</small><small class="ledger-balance">余额:¥ ${money(r.balance)}</small></button>`).join('');}
  function renderIncome(phase){
    let list=entries.filter(r=>(custom?r.date>=rangeStart&&r.date<=rangeEnd:r.month===month)&&(filter==='全部'||(filter==='收入'?r.amount>0:r.amount<0)));
    const months=month==='all'&&!custom?Array.from({length:9},(_,i)=>'2026-'+String(9-i).padStart(2,'0')):custom?[...new Set(list.map(r=>r.month))].sort().reverse():[month];
    return `${top()}<div class="income-filters ledger-filters"><button data-action="income-month">${custom?'自定义':month==='all'?'全部':month.replace('-','.')}▼</button><button data-action="income-card">储蓄卡 0813</button>${month==='all'&&!custom?'<button data-action="income-filter">按金额</button>':''}<button data-action="income-filter">${filter==='全部'?'筛选':filter}</button></div><div class="scroll-area ledger-scroll" data-scroll>${phase!=='ready'?'<div class="income-loading">一大波数据正在赶来，请耐心等待</div>':months.map(m=>{const items=list.filter(r=>r.month===m);return `<section class="ledger-month ${items.length?'':'ledger-empty'}"><h2>${Number(m.slice(5))}月</h2>${items.length?`<p class="ledger-day">${items[0].day}</p>${rows(items)}`:'<span>暂无明细</span>'}</section>`;}).join('')||'<p class="empty">暂无明细</p>'}</div>${tabs()}`;
  }
  function wheel(name,values,value){return `<div class="date-wheel" data-wheel="${name}" tabindex="0" role="listbox" aria-label="${name==='year'?'年份':'月份'}">${values.map(v=>`<button role="option" aria-selected="${v===value}" class="${v===value?'selected':''}" data-action="wheel-option" data-wheel="${name}" data-value="${v}">${v}</button>`).join('')}</div>`;}
  function clampPicker(){year=Math.max(2022,Math.min(2026,year));pickMonth=Math.max(1,Math.min(year===2026?9:12,pickMonth));}
  function picker(){
    clampPicker();
    showModal(`<div class="picker-tabs"><button data-action="picker-tab" data-value="month" class="${pickerMode==='month'?'selected':''}">月份选择</button><button data-action="picker-tab" data-value="custom" class="${pickerMode==='custom'?'selected':''}">自定义</button><button data-action="close" aria-label="关闭">×</button></div>${pickerMode==='month'?`<div class="picker-wheels">${wheel('year',Array.from({length:5},(_,i)=>2022+i),year)}${wheel('month',Array.from({length:year===2026?9:12},(_,i)=>i+1),pickMonth)}</div>`:`<div class="custom-dates"><p>快捷时间</p><div>${['上月','近三月','近一年'].map(x=>`<button data-action="date-shortcut" data-value="${x}">${x}</button>`).join('')}</div><p>自定义</p><label>开始日期<input type="date" data-date="start" value="${rangeStart}" max="${rangeEnd}"></label><label>结束日期<input type="date" data-date="end" value="${rangeEnd}" min="${rangeStart}"></label></div>`}<button class="picker-confirm" data-action="confirm-month">确定</button>`,'month-picker');
    document.querySelectorAll?.('.date-wheel').forEach(el=>{const selectedOption=el.querySelector('[aria-selected="true"]');if(selectedOption)el.scrollTop=[...el.querySelectorAll('button')].indexOf(selectedOption)*selectedOption.offsetHeight;let pending;el.addEventListener('scroll',()=>{clearTimeout(pending);pending=setTimeout(()=>{if(!el.isConnected)return;const options=[...el.querySelectorAll('button')];const h=options[0]?.offsetHeight||1;const index=Math.max(0,Math.min(options.length-1,Math.round(el.scrollTop/h)));options.forEach((b,i)=>{b.classList.toggle('selected',i===index);b.setAttribute('aria-selected',String(i===index));});if(el.dataset.wheel==='year'){const nextYear=Number(options[index].dataset.value);if(nextYear!==year){year=nextYear;picker();}}else{pickMonth=Number(options[index].dataset.value);clampPicker();}},80);},{passive:true});});
  }
  function detail(){selected=entries.find(r=>r.id===getRoute().record)||selected;const r=selected;return `${header('交易详情')}<div class="scroll-area ledger-detail" data-scroll><section class="ledger-detail-amount"><span>${r.amount>0?'⊕ 收入':'⊖ 支出'}</span><strong>${amount(r)}</strong><small>余额 ¥${money(r.balance)}</small></section><dl class="detail-rows">${[['交易卡号','一卡通 6214********0813'],['交易时间',r.date+' '+r.time],...(r.amount>0?[['付款账户','张建生'],['付款账号','尾号8896']]:[]),['交易摘要',r.label],['银行交易类型',r.amount>0?'行内转入':'开户起息']].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><div class="ledger-detail-options"><button data-action="ledger-category"><span>分类</span><span>${r.amount>0?'他人转入':'投资理财'} ›</span></button><button data-action="ledger-book"><span>所属账本</span><span>请选择 ›</span></button><button data-action="ledger-sub"><span>开户子账户</span><span>›</span></button><button data-action="ledger-exclude" role="switch" aria-checked="${excluded.has(r.id)}"><span>不计入本月收支</span><i class="ledger-switch ${excluded.has(r.id)?'on':''}"></i></button><label class="ledger-note">备注<input aria-label="备注" placeholder="" maxlength="100"></label></div><div class="ledger-detail-links"><button data-action="ledger-help">问TA的账</button><button data-action="ledger-voucher">查看电子回单</button></div></div>`;}
  document.addEventListener('change',e=>{if(e.target.dataset?.date==='start')rangeStart=e.target.value;if(e.target.dataset?.date==='end')rangeEnd=e.target.value;});
  function handle(action,b){const v=b.dataset.value;
    if(action==='cash-actions'){showModal(`${[['转账汇款','transfer'],['收支明细','income'],['购买理财','finance'],['购买存款','products'],['转入朝朝宝','finance'],['银行卡管理',null]].map(([label,page])=>`<button class="cash-action" ${page?`data-go="${page}"`:'data-action="income-card"'}>${label}<span>›</span></button>`).join('')}<button class="sheet-cancel" data-action="close">取消</button>`,'cash-sheet');return true;}
    if(action==='income-month'){pickerMode='month';if(month!=='all'){year=Number(month.slice(0,4));pickMonth=Number(month.slice(5));}else{const now=new Date();year=now.getFullYear();pickMonth=now.getMonth()+1;}picker();return true;}
    if(action==='picker-tab'){pickerMode=v;picker();return true;}
    if(action==='wheel-option'){if(b.dataset.wheel==='year')year=Number(v);else pickMonth=Number(v);picker();return true;}
    if(action==='date-shortcut'){rangeEnd='2026-09-05';rangeStart=v==='上月'?'2026-08-01':v==='近三月'?'2026-06-05':'2025-09-05';if(v==='上月')rangeEnd='2026-08-31';picker();return true;}
    if(action==='confirm-month'){clampPicker();if(pickerMode==='custom'&&(!rangeStart||!rangeEnd||rangeStart>rangeEnd))return true;custom=pickerMode==='custom';month=year+'-'+String(pickMonth).padStart(2,'0');navigate({page:'income'},{replace:true});return true;}
    if(action==='set-income-month'){month=v;custom=false;navigate({page:'income'},{replace:true});return true;}
    if(action==='income-filter'){choices('收支类型',['全部','收入','支出'].map(x=>[x,x]),'set-income-filter',filter);return true;}
    if(action==='set-income-filter'){filter=v;navigate({page:'income'},{replace:true});return true;}
    if(action==='income-item'){selected=entries.find(r=>r.id===v)||entries[0];navigate({page:'incomedetail',record:selected.id});return true;}
    if(action==='ledger-exclude'){excluded.has(selected.id)?excluded.delete(selected.id):excluded.add(selected.id);refresh();return true;}
    if(action==='ledger-list'){month='all';custom=false;filter='全部';refresh();return true;}
    const messages={'income-card':['银行卡','储蓄卡 6214********0813'],'ledger-search':['查询收支','请使用月份选择或自定义日期范围查询记录。'],'ledger-book':['账本','暂无账本'],'ledger-category':['分类',selected.amount>0?'他人转入':'投资理财'],'ledger-sub':['开户子账户','一卡通 0813'],'ledger-help':['交易查询',selected.label],'ledger-voucher':['电子回单','参考素材未包含本笔交易的电子回单。']};
    if(messages[action]){service(...messages[action]);return true;}return false;
  }
  return {render:renderIncome,detail,handle,resetFilters(){month='all';filter='全部';custom=false;},reset(){month='all';filter='全部';custom=false;excluded.clear();entries.forEach(r=>excluded.add(r.id));}};
};
